INSERT INTO people
	(firstname, lastname)
VALUES
	('William', 'Shakespeare')
	,('Agatha', 'Christie')
	,('Barbara', 'Cartland')
	,('Danielle', 'Steel')
	,('Harold', 'Robbins')
	,('Georges', 'Simenon')
	,('Enid', 'Blyton')
	,('J. K.', 'Rowling')
	,('Sidney', 'Sheldon')
	,('Eiichiro', 'Oda')
	,('Gilbert', 'Patten')
	,('Tom', 'Clancy')
	,('Dr.', 'Seuss')
	,('Akira', 'Toriyama')
	,('Leo', 'Tolstoy')
	,('Corín', 'Tellado')
	,('Dean', 'Koontz')
	,('Jackie', 'Collins')
	,('Horatio', 'Alger')
	,('Nora', 'Roberts')
	,('R. L.', 'Stine')
	,('Alexander', 'Pushkin')
	,('Stephen', 'King')
	,('Paulo', 'Coelho')
	,('Jirō', 'Akagawa')
	,('Jeffrey', 'Archer')
	,('Louis', $$L\'Amour$$)
	,('René', 'Goscinny')
	,('Erle Stanley', 'Gardner')
	,('Edgar', 'Wallace')
	,('Janet', 'Dailey')
	,('Jin', 'Yong')
	,('Robert', 'Ludlum')
	,('Osamu', 'Tezuka')
	,('James', 'Patterson')
	,('Frédéric', 'Dard')
	,('Stan and Jan', 'Berenstain')
	,('Roald', 'Dahl')
	,('John', 'Grisham')
	,('Zane', 'Grey')
	,('Irving', 'Wallace')
	,('J. R. R.', 'Tolkien')
	,('Masashi', 'Kishimoto')
	,('Gosho', 'Aoyama')
	,('Karl', 'May')
	,('Mickey', 'Spillane')
	,('C. S.', 'Lewis')
	,('Kyotaro', 'Nishimura')
	,('Mitsuru', 'Adachi')
	,('Rumiko', 'Takahashi')
	,('Dan', 'Brown')
	,('Alistair', 'MacLean')
	,('Ann M.', 'Martin')
	,('Ryōtarō', 'Shiba')
	,('Arthur', 'Hailey')
	,('Astrid', 'Lindgren')
	,('Koyoharu', 'Gotouge')
	,('Anne', 'Rice')
	,('Gérard de', 'Villiers')
	,('Beatrix', 'Potter')
	,('Michael', 'Crichton')
	,('Richard', 'Scarry')
	,('Clive', 'Cussler')
	,('Ken', 'Follett')
	,('Debbie', 'Macomber')
	,('Naoki', 'Urasawa')
	,('EL', 'James')
	,('Carter', 'Brown')
	,('Tite', 'Kubo')
	,('Eiji', 'Yoshikawa')
	,('Hajime', 'Isayama')
	,('Catherine', 'Cookson')
	,('Stephenie', 'Meyer')
	,('Norman', 'Bridwell')
	,('David', 'Baldacci')
	,('Nicholas', 'Sparks')
	,('Hirohiko', 'Araki')
	,('Evan', 'Hunter')
	,('Andrew', 'Neiderman')
	,('Roger', 'Hargreaves')
	,('Robin', 'Cook')
	,('Wilbur', 'Smith')
	,('Erskine', 'Caldwell')
	,('Judith', 'Krantz')
	,('Eleanor', 'Hibbert')
	,('Lewis', 'Carroll')
	,('Denise', 'Robins')
	,('Cao', 'Xueqin')
	,('Ian', 'Fleming')
	,('Hermann', 'Hesse')
	,('Rex', 'Stout')
	,('Anne', 'Golon')
	,('Frank G.', 'Slaughter')
	,('Edgar Rice', 'Burroughs')
	,('John', 'Creasey')
	,('James A.', 'Michener')
	,('Yasuo', 'Uchida')
	,('Seiichi', 'Morimura')
	,('Mary Higgins', 'Clark')
	,('Penny', 'Jordan')
	,('Patricia', 'Cornwell')
	,('Terry', 'Pratchett')
;
